spring.application.name=notification
server.port=8084
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singh017deepak@gmail.com
spring.mail.password=xtpsckdgrpvjwrkl
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.file.name=logs/application.log
logging.level.org.springframework=DEBUG
logging.level.com.flight.notification=DEBUG
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.mail=DEBUG


logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.max-size=10MB
logging.file.max-history=30

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka